// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCredentials = `-- name: CreateCredentials :one
INSERT INTO credentials (user_id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING user_id
`

type CreateCredentialsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCredentials, arg.UserID, arg.Email, arg.PasswordHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const findByEmail = `-- name: FindByEmail :one
SELECT user_id, email, password_hash FROM credentials
WHERE email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (Credential, error) {
	row := q.db.QueryRow(ctx, findByEmail, email)
	var i Credential
	err := row.Scan(&i.UserID, &i.Email, &i.PasswordHash)
	return i, err
}
