// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

type RefreshToken struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	IsRevoked pgtype.Bool `json:"is_revoked"`
}
