// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthCredential = `-- name: CreateOAuthCredential :one
INSERT INTO oauth_credentials(user_id, provider, provider_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_id
`

type CreateOAuthCredentialParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
}

func (q *Queries) CreateOAuthCredential(ctx context.Context, arg CreateOAuthCredentialParams) (OauthCredential, error) {
	row := q.db.QueryRow(ctx, createOAuthCredential, arg.UserID, arg.Provider, arg.ProviderID)
	var i OauthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const findByProvider = `-- name: FindByProvider :one
SELECT id, user_id, provider, provider_id FROM oauth_credentials
WHERE provider = $1 and provider_id = $2
`

type FindByProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) FindByProvider(ctx context.Context, arg FindByProviderParams) (OauthCredential, error) {
	row := q.db.QueryRow(ctx, findByProvider, arg.Provider, arg.ProviderID)
	var i OauthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}
