// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_tokens(user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findByUserID = `-- name: FindByUserID :one
SELECT id, user_id, token_hash, expires_at, is_revoked FROM refresh_tokens
WHERE user_id = $1 and is_revoked = FALSE
`

func (q *Queries) FindByUserID(ctx context.Context, userID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
	)
	return i, err
}
