services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - gateway

  db-user:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d user_db"]
        interval: 5s
        timeout: 5s
        retries: 5

  db-auth:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${DB_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_AUTH} -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-task:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: ${DB_TASK}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${TASK_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_TASK} -d task_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-notification:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: ${DB_NOTIFICATION}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${NOTIFICATION_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_NOTIFICATION} -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    env_file: user-service/.env
    depends_on:
      db-user:
        condition: service_healthy

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    env_file: auth-service/.env
    depends_on:
      user-service:
        condition: service_started
      db-auth:
        condition: service_healthy

  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    env_file: task-service/.env
    depends_on:
      db-task:
        condition: service_healthy

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    env_file: notification-service/.env
    depends_on:
      db-notification:
        condition: service_healthy
      kafka:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file: gateway/.env
    depends_on:
      - user-service
      - auth-service
      - task-service
      - notification-service
    ports:
      - "${GATEWAY_PORT}:8080"

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka-broker
    ports:
      - "9094:9094"
    environment:
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9093:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
