// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Provider  string             `json:"provider"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserContact struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
	Contact  string    `json:"contact"`
}
