// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const saveNotification = `-- name: SaveNotification :one
INSERT INTO notifications(user_id, type, provider)
VALUES ($1, $2, $3)
RETURNING id, user_id, type, provider, created_at
`

type SaveNotificationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Type     string    `json:"type"`
	Provider string    `json:"provider"`
}

func (q *Queries) SaveNotification(ctx context.Context, arg SaveNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, saveNotification, arg.UserID, arg.Type, arg.Provider)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}
