// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getStatistics = `-- name: GetStatistics :many
SELECT type, provider, DATE(created_at) as date,
       COUNT(distinct user_id) AS unique_hits,
       COUNT(*) AS total_hits
FROM notifications
WHERE ($1::text IS NULL OR provider = $1::text)
AND ($2::timestamptz IS NULL OR DATE(created_at) = DATE($2::timestamptz))
GROUP BY type, provider, DATE(created_at)
`

type GetStatisticsParams struct {
	Provider pgtype.Text        `json:"provider"`
	Date     pgtype.Timestamptz `json:"date"`
}

type GetStatisticsRow struct {
	Type       string      `json:"type"`
	Provider   string      `json:"provider"`
	Date       pgtype.Date `json:"date"`
	UniqueHits int64       `json:"unique_hits"`
	TotalHits  int64       `json:"total_hits"`
}

func (q *Queries) GetStatistics(ctx context.Context, arg GetStatisticsParams) ([]GetStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getStatistics, arg.Provider, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatisticsRow
	for rows.Next() {
		var i GetStatisticsRow
		if err := rows.Scan(
			&i.Type,
			&i.Provider,
			&i.Date,
			&i.UniqueHits,
			&i.TotalHits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNotification = `-- name: SaveNotification :one
INSERT INTO notifications(user_id, type, provider)
VALUES ($1, $2, $3)
RETURNING id, user_id, type, provider, created_at
`

type SaveNotificationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Type     string    `json:"type"`
	Provider string    `json:"provider"`
}

func (q *Queries) SaveNotification(ctx context.Context, arg SaveNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, saveNotification, arg.UserID, arg.Type, arg.Provider)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}
