// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_contact.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getContact = `-- name: GetContact :one
SELECT contact from user_contacts
WHERE user_id = $1 and provider = $2
`

type GetContactParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (string, error) {
	row := q.db.QueryRow(ctx, getContact, arg.UserID, arg.Provider)
	var contact string
	err := row.Scan(&contact)
	return contact, err
}

const saveContact = `-- name: SaveContact :one
INSERT INTO user_contacts(user_id, provider, contact)
VALUES ($1, $2, $3)
RETURNING user_id, provider, contact
`

type SaveContactParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
	Contact  string    `json:"contact"`
}

func (q *Queries) SaveContact(ctx context.Context, arg SaveContactParams) (UserContact, error) {
	row := q.db.QueryRow(ctx, saveContact, arg.UserID, arg.Provider, arg.Contact)
	var i UserContact
	err := row.Scan(&i.UserID, &i.Provider, &i.Contact)
	return i, err
}
