  server {
      listen 80;
      server_name keeperofthelight.su;
      return 301 https://$host$request_uri;
  }

  server {
      listen 443 ssl;
      server_name keeperofthelight.su;

      ssl_certificate     /etc/letsencrypt/live/keeperofthelight.su/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/keeperofthelight.su/privkey.pem;

      root /usr/share/nginx/html;
      index index.html;

      location / {
          try_files $uri $uri/ /index.html;
      }

      location ~ ^/(login|logout|register|refresh|users|tasks) {
          proxy_pass http://gateway:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }