// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email)
VALUES ($1, $2)
RETURNING id, name, email
`

type CreateUserParams struct {
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
}

type CreateUserRow struct {
	ID    uuid.UUID   `json:"id"`
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET deleted_at = now(), updated_at = now()
WHERE deleted_at IS NULL and id = $1
RETURNING name, email
`

type DeleteUserRow struct {
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (DeleteUserRow, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i DeleteUserRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL and id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3, updated_at = now()
WHERE deleted_at IS NULL and id = $1
RETURNING name, email
`

type UpdateUserParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
}

type UpdateUserRow struct {
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	var i UpdateUserRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}
