// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, description, status, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.UserID, arg.Title, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTasks = `-- name: DeleteTasks :many
UPDATE tasks
SET deleted_at = now(), updated_at = now()
WHERE deleted_at IS NULL AND id = ANY($1::uuid[]) AND user_id = $2
RETURNING id, user_id, title, description, status, created_at, updated_at, deleted_at
`

type DeleteTasksParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	UserID  uuid.UUID   `json:"user_id"`
}

func (q *Queries) DeleteTasks(ctx context.Context, arg DeleteTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, deleteTasks, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyTaskSummary = `-- name: GetDailyTaskSummary :many
SELECT user_id,
       COUNT(*) FILTER (WHERE status = 'done') AS done_count,
       COUNT(*) FILTER (WHERE status = 'in_progress') AS in_progress_count
FROM tasks
WHERE deleted_at IS NULL AND (
    status = 'in_progress' OR
    (status = 'done' AND DATE(updated_at) = DATE(NOW()))
    )
GROUP BY user_id
`

type GetDailyTaskSummaryRow struct {
	UserID          uuid.UUID `json:"user_id"`
	DoneCount       int64     `json:"done_count"`
	InProgressCount int64     `json:"in_progress_count"`
}

func (q *Queries) GetDailyTaskSummary(ctx context.Context) ([]GetDailyTaskSummaryRow, error) {
	rows, err := q.db.Query(ctx, getDailyTaskSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyTaskSummaryRow
	for rows.Next() {
		var i GetDailyTaskSummaryRow
		if err := rows.Scan(&i.UserID, &i.DoneCount, &i.InProgressCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, title, description, status, created_at, updated_at, deleted_at FROM tasks
WHERE deleted_at IS NULL AND id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, description, status, created_at, updated_at, deleted_at FROM tasks
WHERE deleted_at IS NULL AND user_id = $1
AND ($2::task_status IS NULL OR status = $2::task_status)
AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
ORDER BY created_at DESC
LIMIT $4
`

type ListTasksParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Status NullTaskStatus     `json:"status"`
	Cursor pgtype.Timestamptz `json:"cursor"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.UserID,
		arg.Status,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, description = $3, status = $4, updated_at = now()
WHERE deleted_at IS NULL AND id = $1
RETURNING id, user_id, title, description, status, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      TaskStatus  `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
