// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, status)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, status
`

type CreateTaskParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      TaskStatus  `json:"status"`
}

type CreateTaskRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      TaskStatus  `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const deleteTasks = `-- name: DeleteTasks :many
UPDATE tasks
SET deleted_at = now(), updated_at = now()
WHERE deleted_at IS NULL and id = ANY($1::uuid[])
RETURNING id, title, description, status
`

type DeleteTasksRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      TaskStatus  `json:"status"`
}

func (q *Queries) DeleteTasks(ctx context.Context, dollar_1 []uuid.UUID) ([]DeleteTasksRow, error) {
	rows, err := q.db.Query(ctx, deleteTasks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteTasksRow
	for rows.Next() {
		var i DeleteTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, title, description, status, created_at, updated_at, deleted_at FROM tasks
WHERE deleted_at IS NULL AND id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, description, status, created_at, updated_at, deleted_at FROM tasks
WHERE deleted_at IS NULL AND user_id = $1
AND ($2::task_status IS NULL OR status = $2)
AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListTasksParams struct {
	UserID  uuid.UUID  `json:"user_id"`
	Column2 TaskStatus `json:"column_2"`
	Column3 time.Time  `json:"column_3"`
	Limit   int32      `json:"limit"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, description = $3, status = $4, updated_at = now()
WHERE deleted_at IS NULL AND id = $1
RETURNING id, title, description, status
`

type UpdateTaskParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      TaskStatus  `json:"status"`
}

type UpdateTaskRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      TaskStatus  `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
	)
	return i, err
}
